# Generated by Django 5.1.1 on 2026-02-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprofile_position_userposition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userposition",
            options={
                "ordering": ["-start_date", "-end_date"],
                "verbose_name": "User position",
                "verbose_name_plural": "User positions",
            },
        ),
        migrations.AlterField(
            model_name="userposition",
            name="start_date",
            field=models.DateField(
                default="2020-01-01",
                help_text="The start date for this user's position",
                verbose_name="Start date",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="userposition",
            index=models.Index(
                fields=["user_profile", "end_date"],
                name="users_userp_user_pr_0ae428_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userposition",
            index=models.Index(
                fields=["position", "end_date"], name="users_userp_positio_40c984_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userposition",
            index=models.Index(
                fields=["start_date"], name="users_userp_start_d_c03cf9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("user_profile",),
                name="one_current_position_per_user",
            ),
        ),
    ]
