# Generated by Django 5.1.1 on 2025-12-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0019_project_counts_for_main_funding'),
        ('users', '0012_alter_userprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamarea',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='team_areas', to='metrics.project'),
        ),
    ]
