# Generated by Django 5.1.1 on 2025-12-24 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('metrics', '0019_project_counts_for_main_funding'),
        ('users', '0013_teamarea_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['text'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='teamarea',
            options={'ordering': ['text'], 'verbose_name': 'Team area', 'verbose_name_plural': 'Team areas'},
        ),
        migrations.RemoveField(
            model_name='teamarea',
            name='color_code',
        ),
        migrations.AddField(
            model_name='position',
            name='text_en',
            field=models.CharField(help_text='Human-readable name of the position', max_length=420, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='position',
            name='text_es',
            field=models.CharField(help_text='Human-readable name of the position', max_length=420, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='position',
            name='text_pt_br',
            field=models.CharField(help_text='Human-readable name of the position', max_length=420, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teamarea',
            name='text_en',
            field=models.CharField(help_text='Human-readable name of the team area', max_length=420, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teamarea',
            name='text_es',
            field=models.CharField(help_text='Human-readable name of the team area', max_length=420, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teamarea',
            name='text_pt_br',
            field=models.CharField(help_text='Human-readable name of the team area', max_length=420, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='area_associated',
            field=models.ForeignKey(help_text='The team area this position belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='users.teamarea', verbose_name='Team Area'),
        ),
        migrations.AlterField(
            model_name='position',
            name='text',
            field=models.CharField(help_text='Human-readable name of the position', max_length=420, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.ForeignKey(help_text='The permission group this position belongs to', on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Permission group'),
        ),
        migrations.AlterField(
            model_name='teamarea',
            name='code',
            field=models.CharField(help_text='Short identifier of a CSS class of the team area', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='teamarea',
            name='project',
            field=models.ManyToManyField(blank=True, help_text='The projects this team area belongs to', related_name='team_areas', to='metrics.project', verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='teamarea',
            name='text',
            field=models.CharField(help_text='Human-readable name of the team area', max_length=420, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary'), ('other', 'Other'), ('not_declared', 'Not declared')], default='not_declared', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_scholar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Google Scholar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lattes',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lattes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_wiki_handle',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Personal username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photograph',
            field=models.CharField(blank=True, default='', max_length=420, verbose_name='Photograph filename'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(blank=True, help_text='The position this user belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professional_wiki_handle',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Professional username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text="The user which this profile's about", on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wikidata_item',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Wikidata item'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('area_associated', 'text'), ('area_associated', 'text_en'), ('area_associated', 'text_es'), ('area_associated', 'text_pt_br')},
        ),
    ]
