# Generated by Django 5.1.1 on 2026-01-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_position_options_alter_teamarea_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', help_text='Facebook handle', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_scholar',
            field=models.CharField(blank=True, default='', help_text='Google Scholar ID', max_length=100, verbose_name='Google Scholar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, default='', help_text='Instagram handle', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lattes',
            field=models.CharField(blank=True, default='', help_text='Lattes ID', max_length=100, verbose_name='Lattes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='LinkedIn handle', max_length=100, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, default='', help_text='ORCID ID', max_length=100, verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Twitter handle', max_length=100, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wikidata_item',
            field=models.CharField(blank=True, default='', help_text='Wikidata QID', max_length=100, verbose_name='Wikidata item'),
        ),
    ]
