# Generated by Django 5.1.1 on 2026-01-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Human-readable name of the learning area.', max_length=420, verbose_name='Text')),
                ('text_en', models.CharField(help_text='Human-readable name of the learning area.', max_length=420, null=True, verbose_name='Text')),
                ('text_pt_br', models.CharField(help_text='Human-readable name of the learning area.', max_length=420, null=True, verbose_name='Text')),
                ('text_es', models.CharField(help_text='Human-readable name of the learning area.', max_length=420, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Learning area',
                'verbose_name_plural': 'Learning areas',
            },
        ),
        migrations.CreateModel(
            name='StrategicAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, verbose_name='Text')),
                ('text_en', models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, null=True, verbose_name='Text')),
                ('text_pt_br', models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, null=True, verbose_name='Text')),
                ('text_es', models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, null=True, verbose_name='Text')),
                ('intentionality', models.CharField(blank=True, help_text='Explanation of the intentionality behind this axis.', max_length=420, null=True, verbose_name='Intentionality')),
            ],
            options={
                'verbose_name': 'Strategic axis',
                'verbose_name_plural': 'Strategic axes',
            },
        ),
        migrations.CreateModel(
            name='EvaluationObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, verbose_name='Text')),
                ('text_en', models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, null=True, verbose_name='Text')),
                ('text_pt_br', models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, null=True, verbose_name='Text')),
                ('text_es', models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, null=True, verbose_name='Text')),
                ('learning_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_objective', to='strategy.learningarea', verbose_name='Learning area')),
            ],
            options={
                'verbose_name': 'Evaluation objective',
                'verbose_name_plural': 'Evaluation objectives',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Human-readable name of the direction.', max_length=420, verbose_name='Text')),
                ('text_en', models.CharField(help_text='Human-readable name of the direction.', max_length=420, null=True, verbose_name='Text')),
                ('text_pt_br', models.CharField(help_text='Human-readable name of the direction.', max_length=420, null=True, verbose_name='Text')),
                ('text_es', models.CharField(help_text='Human-readable name of the direction.', max_length=420, null=True, verbose_name='Text')),
                ('strategic_axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='strategy.strategicaxis', verbose_name='Strategic axis')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
            },
        ),
        migrations.CreateModel(
            name='StrategicLearningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Human-readable name of the learning question.', max_length=420, verbose_name='Text')),
                ('text_en', models.CharField(help_text='Human-readable name of the learning question.', max_length=420, null=True, verbose_name='Text')),
                ('text_pt_br', models.CharField(help_text='Human-readable name of the learning question.', max_length=420, null=True, verbose_name='Text')),
                ('text_es', models.CharField(help_text='Human-readable name of the learning question.', max_length=420, null=True, verbose_name='Text')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_question', to='strategy.learningarea', verbose_name='Learning area')),
            ],
            options={
                'verbose_name': 'Strategic learning question',
                'verbose_name_plural': 'Strategic learning questions',
            },
        ),
    ]
