# Generated by Django 5.1.1 on 2026-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicaxis',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this axis is from the active Strategy.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this learning area is from the active Strategy.',
                                      verbose_name='Active'),
        ),
    ]
