# Generated by Django 5.1.1 on 2026-01-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_strategicaxis_intentionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='text_en',
            field=models.CharField(help_text='Human-readable name of the direction.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='direction',
            name='text_es',
            field=models.CharField(help_text='Human-readable name of the direction.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='direction',
            name='text_pt_br',
            field=models.CharField(help_text='Human-readable name of the direction.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='strategicaxis',
            name='text_en',
            field=models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='strategicaxis',
            name='text_es',
            field=models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='strategicaxis',
            name='text_pt_br',
            field=models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='strategic_axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='strategy.strategicaxis', verbose_name='Strategic axis'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='text',
            field=models.CharField(help_text='Human-readable name of the direction.', max_length=420, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='strategicaxis',
            name='intentionality',
            field=models.CharField(blank=True, help_text='Explanation of the intentionality behind this axis.', max_length=420, null=True, verbose_name='Intentionality'),
        ),
        migrations.AlterField(
            model_name='strategicaxis',
            name='text',
            field=models.CharField(help_text='Human-readable name of the Strategic axis.', max_length=420, verbose_name='Text'),
        ),
    ]
