# Generated by Django 5.1.1 on 2026-01-05 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_direction_text_en_direction_text_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
            ],
            options={
                'verbose_name': 'Learning area',
                'verbose_name_plural': 'Learning areas',
            },
        ),
        migrations.CreateModel(
            name='EvaluationObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
                ('learning_area_of_objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_objective', to='strategy.learningarea')),
            ],
            options={
                'verbose_name': 'Evaluation objective',
                'verbose_name_plural': 'Evaluation objectives',
            },
        ),
        migrations.CreateModel(
            name='StrategicLearningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=420)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_question', to='strategy.learningarea')),
            ],
            options={
                'verbose_name': 'Strategic learning question',
                'verbose_name_plural': 'Strategic learning questions',
            },
        ),
    ]
