# Generated by Django 5.1.1 on 2026-01-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_learningarea_evaluationobjective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationobjective',
            name='learning_area_of_objective',
        ),
        migrations.AddField(
            model_name='evaluationobjective',
            name='learning_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_objective', to='strategy.learningarea', verbose_name='Learning area'),
        ),
        migrations.AddField(
            model_name='evaluationobjective',
            name='text_en',
            field=models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='evaluationobjective',
            name='text_es',
            field=models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='evaluationobjective',
            name='text_pt_br',
            field=models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='text_en',
            field=models.CharField(help_text='Human-readable name of the learning area.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='text_es',
            field=models.CharField(help_text='Human-readable name of the learning area.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='text_pt_br',
            field=models.CharField(help_text='Human-readable name of the learning area.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='strategiclearningquestion',
            name='text_en',
            field=models.CharField(help_text='Human-readable name of the learning question.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='strategiclearningquestion',
            name='text_es',
            field=models.CharField(help_text='Human-readable name of the learning question.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='strategiclearningquestion',
            name='text_pt_br',
            field=models.CharField(help_text='Human-readable name of the learning question.', max_length=420, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='evaluationobjective',
            name='text',
            field=models.CharField(help_text='Human-readable name of the evaluation objective.', max_length=420, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='learningarea',
            name='text',
            field=models.CharField(help_text='Human-readable name of the learning area.', max_length=420, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='strategiclearningquestion',
            name='learning_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_question', to='strategy.learningarea', verbose_name='Learning area'),
        ),
        migrations.AlterField(
            model_name='strategiclearningquestion',
            name='text',
            field=models.CharField(help_text='Human-readable name of the learning question.', max_length=420, verbose_name='Text'),
        ),
    ]
