sonar.projectKey=WikiMovimentoBrasil_sara
sonar.organization=wikimovimentobrasil
sonar.sources=.
sonar.exclusions=**/migrations/**
sonar.cpd.exclusions=**/migrations/**,**/tests.py,**/tests/**,**/tests_*.py.
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=sara/**,app.py,manage.py
sonar.sourceEncoding=UTF-8
