# Generated by Django 5.1.1 on 2026-01-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area_responsible',
            field=models.ForeignKey(help_text='Area responsible for the event', on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='users.teamarea', verbose_name='Area responsible'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('initial_date'))), name='event_end_date_after_start_date'),
        ),
    ]
