# Generated by Django 5.1.1 on 2026-01-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_event_activity_associated'),
        ('users', '0015_alter_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['initial_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='activity_associated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='area_involved',
        ),
        migrations.RemoveField(
            model_name='event',
            name='metric_associated',
        ),
        migrations.AlterField(
            model_name='event',
            name='area_responsible',
            field=models.ForeignKey(help_text='Area responsible for the event', on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='users.teamarea', verbose_name='Area responsible'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(help_text='Date of the ending of the event', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initial_date',
            field=models.DateField(help_text='Date of the beginning of the event', verbose_name='Initial date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Title of the event', max_length=420, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('initial_date'))), name='event_end_date_after_start_date'),
        ),
    ]
