# Generated by Django 5.1.1 on 2026-01-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaActivated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=420, verbose_name='Name of the area activated')),
                ('contact', models.TextField(blank=True, max_length=420, null=True)),
            ],
            options={
                'verbose_name': 'Area activated',
                'verbose_name_plural': 'Areas activated',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=420)),
                ('retained', models.BooleanField(default=False)),
                ('retained_at', models.DateField(blank=True, null=True)),
                ('account_creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editors',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='project_related', to='metrics.project')),
            ],
            options={
                'verbose_name': 'Funding',
                'verbose_name_plural': 'Fundings',
            },
        ),
        migrations.CreateModel(
            name='OperationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people_reached_through_social_media', models.IntegerField(blank=True, default=0)),
                ('number_of_new_followers', models.IntegerField(blank=True, default=0)),
                ('number_of_mentions', models.IntegerField(blank=True, default=0)),
                ('number_of_community_communications', models.IntegerField(blank=True, default=0)),
                ('number_of_events', models.IntegerField(blank=True, default=0)),
                ('number_of_resources', models.IntegerField(blank=True, default=0)),
                ('number_of_partnerships_activated', models.IntegerField(blank=True, default=0)),
                ('number_of_new_partnerships', models.IntegerField(blank=True, default=0)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operation_metric', to='metrics.metric')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=420)),
                ('retained', models.BooleanField(default=False)),
                ('institution', models.ManyToManyField(related_name='organizer_institution', to='report.partner')),
            ],
            options={
                'verbose_name': 'Organizer',
                'verbose_name_plural': 'Organizers',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('reference_text', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('partial_report', models.BooleanField(blank=True, default=False)),
                ('activity_other', models.TextField(blank=True, default='', max_length=420)),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=420)),
                ('links', models.TextField(max_length=10000)),
                ('private_links', models.BooleanField(blank=True, default=False)),
                ('public_communication', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('wikipedia_created', models.IntegerField(blank=True, default=0)),
                ('wikipedia_edited', models.IntegerField(blank=True, default=0)),
                ('commons_created', models.IntegerField(blank=True, default=0)),
                ('commons_edited', models.IntegerField(blank=True, default=0)),
                ('wikidata_created', models.IntegerField(blank=True, default=0)),
                ('wikidata_edited', models.IntegerField(blank=True, default=0)),
                ('wikiversity_created', models.IntegerField(blank=True, default=0)),
                ('wikiversity_edited', models.IntegerField(blank=True, default=0)),
                ('wikibooks_created', models.IntegerField(blank=True, default=0)),
                ('wikibooks_edited', models.IntegerField(blank=True, default=0)),
                ('wikisource_created', models.IntegerField(blank=True, default=0)),
                ('wikisource_edited', models.IntegerField(blank=True, default=0)),
                ('wikinews_created', models.IntegerField(blank=True, default=0)),
                ('wikinews_edited', models.IntegerField(blank=True, default=0)),
                ('wikiquote_created', models.IntegerField(blank=True, default=0)),
                ('wikiquote_edited', models.IntegerField(blank=True, default=0)),
                ('wiktionary_created', models.IntegerField(blank=True, default=0)),
                ('wiktionary_edited', models.IntegerField(blank=True, default=0)),
                ('wikivoyage_created', models.IntegerField(blank=True, default=0)),
                ('wikivoyage_edited', models.IntegerField(blank=True, default=0)),
                ('wikispecies_created', models.IntegerField(blank=True, default=0)),
                ('wikispecies_edited', models.IntegerField(blank=True, default=0)),
                ('metawiki_created', models.IntegerField(blank=True, default=0)),
                ('metawiki_edited', models.IntegerField(blank=True, default=0)),
                ('mediawiki_created', models.IntegerField(blank=True, default=0)),
                ('mediawiki_edited', models.IntegerField(blank=True, default=0)),
                ('participants', models.IntegerField(blank=True, default=0)),
                ('feedbacks', models.IntegerField(blank=True, default=0)),
                ('learning', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('donors', models.IntegerField(default=0, null=True)),
                ('submissions', models.IntegerField(default=0, null=True)),
                ('activity_associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='report_activity', to='metrics.activity')),
                ('area_activated', models.ManyToManyField(blank=True, related_name='area_activated', to='report.areaactivated')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'permissions': [('can_edit_locked_report', 'Can edit locked report')],
            },
        ),
    ]
