# Generated by Django 5.1.1 on 2026-01-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0002_initial'),
        ('report', '0001_initial'),
        ('strategy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='area_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsible', to='users.teamarea'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_reporting', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='report',
            name='directions_related',
            field=models.ManyToManyField(blank=True, related_name='direction_related', to='strategy.direction'),
        ),
        migrations.AddField(
            model_name='report',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to='report.editor'),
        ),
        migrations.AddField(
            model_name='report',
            name='funding_associated',
            field=models.ManyToManyField(blank=True, related_name='funding_associated', to='report.funding'),
        ),
        migrations.AddField(
            model_name='report',
            name='learning_questions_related',
            field=models.ManyToManyField(blank=True, related_name='strategic_learning_question_related', to='strategy.strategiclearningquestion'),
        ),
        migrations.AddField(
            model_name='report',
            name='metrics_related',
            field=models.ManyToManyField(related_name='metrics_related', to='metrics.metric'),
        ),
        migrations.AddField(
            model_name='report',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_modifying', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='report',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizers', to='report.organizer'),
        ),
        migrations.AddField(
            model_name='report',
            name='partners_activated',
            field=models.ManyToManyField(blank=True, related_name='partners', to='report.partner'),
        ),
        migrations.AddField(
            model_name='operationreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_report', to='report.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, related_name='tecnologies', to='report.technology'),
        ),
    ]
