# Generated by Django 5.1.1 on 2026-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='username',
            field=models.CharField(max_length=420, unique=True),
        ),
    ]
