# Generated by Django 5.1.1 on 2026-01-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metrics", "0002_initial"),
        ("report", "0001_initial"),
        ("strategy", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="area_activated",
            field=models.ManyToManyField(
                blank=True,
                help_text="The areas activated for the activity",
                related_name="area_activated",
                to="users.teamarea",
                verbose_name="Areas activated",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="area_responsible",
            field=models.ForeignKey(
                help_text="The area responsible for the report",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="responsible",
                to="users.teamarea",
                verbose_name="Area responsible",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created the report",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="user_reporting",
                to="users.userprofile",
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="directions_related",
            field=models.ManyToManyField(
                blank=True,
                help_text="Directions guiding the activity reported.",
                related_name="direction_related",
                to="strategy.direction",
                verbose_name="Directions related",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Editors registered of the activity reported.",
                related_name="editors",
                to="report.editor",
                verbose_name="Editors",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="funding_associated",
            field=models.ManyToManyField(
                blank=True,
                help_text="The funding associated with the activity",
                related_name="funding_associated",
                to="report.funding",
                verbose_name="Funding associated",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="learning_questions_related",
            field=models.ManyToManyField(
                blank=True,
                help_text="Strategic learning questions the activity reported tries to answer or reflects on.",
                related_name="strategic_learning_question_related",
                to="strategy.strategiclearningquestion",
                verbose_name="Strategic Learning Question",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="metrics_related",
            field=models.ManyToManyField(
                help_text="Metrics guiding the activity reported.",
                related_name="metrics_related",
                to="metrics.metric",
                verbose_name="Metrics related",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user who modified the report",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="user_modifying",
                to="users.userprofile",
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="organizers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organizers registered of the activity reported.",
                related_name="organizers",
                to="report.organizer",
                verbose_name="Organizers",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="partners_activated",
            field=models.ManyToManyField(
                blank=True,
                help_text="Formal partners (institutions) activated of the activity reported.",
                related_name="partners",
                to="report.partner",
                verbose_name="Partnerships activated",
            ),
        ),
        migrations.AddField(
            model_name="operationreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_report",
                to="report.report",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="technologies_used",
            field=models.ManyToManyField(
                blank=True,
                help_text="Technologies used on the activity reported.",
                related_name="technologies",
                to="report.technology",
                verbose_name="Technologies used",
            ),
        ),
    ]
