# Generated by Django 5.1.1 on 2026-01-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_organizer_first_seen_at_organizer_retained_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='first_seen_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
