# Generated by Django 5.2.15 on 2026-08-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_editor_first_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='learning',
            field=models.TextField(blank=True, default='', help_text='Specific learning about the activity reported.', max_length=5000, verbose_name='Learning'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reference_text',
            field=models.TextField(blank=True, default='', help_text='The reference text of the report, in wikitext', max_length=10000, verbose_name='Reference text'),
        ),
    ]
