# Generated by Django 5.1.1 on 2025-07-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0040_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
