# Generated by Django 5.1.1 on 2025-07-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0041_report_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='retained_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
