# Generated by Django 5.1.1 on 2025-08-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0042_editor_retained_at'),
        ('strategy', '0002_strategicaxis_intentionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='directions_related',
            field=models.ManyToManyField(blank=True, related_name='direction_related', to='strategy.direction'),
        ),
        migrations.AlterField(
            model_name='report',
            name='learning_questions_related',
            field=models.ManyToManyField(blank=True, related_name='strategic_learning_question_related', to='report.strategiclearningquestion'),
        ),
    ]
