# Generated by Django 5.1.1 on 2026-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0043_alter_report_directions_related_and_more'),
        ('strategy', '0004_learningarea_evaluationobjective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategiclearningquestion',
            name='learning_area',
        ),
        migrations.AlterField(
            model_name='report',
            name='learning_questions_related',
            field=models.ManyToManyField(blank=True, related_name='strategic_learning_question_related', to='strategy.strategiclearningquestion'),
        ),
        migrations.DeleteModel(
            name='EvaluationObjective',
        ),
        migrations.DeleteModel(
            name='LearningArea',
        ),
        migrations.DeleteModel(
            name='StrategicLearningQuestion',
        ),
    ]
