# Generated by Django 5.1.1 on 2026-01-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='other_type',
        ),
    ]
