# Generated by Django 5.1.1 on 2026-02-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_alter_activity_is_main_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="commons_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of medias created on Wikimedia Commons.",
                null=True,
                verbose_name="Created in Wikimedia Commons",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="commons_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of medias edited on Wikimedia Commons.",
                null=True,
                verbose_name="Edited in Wikimedia Commons",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="incubator_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikimedia Incubator.",
                null=True,
                verbose_name="Created in Wikimedia Incubator",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="incubator_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikimedia Incubator.",
                null=True,
                verbose_name="Edited in Wikimedia Incubator",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="mediawiki_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Mediawiki.",
                null=True,
                verbose_name="Created in Mediawiki",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="mediawiki_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Mediawiki.",
                null=True,
                verbose_name="Edited in Mediawiki",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="metawiki_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Meta-Wiki.",
                null=True,
                verbose_name="Created in Meta-Wiki",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="metawiki_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Meta-Wiki.",
                null=True,
                verbose_name="Edited in Meta-Wiki",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikibooks_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikibooks.",
                null=True,
                verbose_name="Created in Wikibooks",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikibooks_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikibooks.",
                null=True,
                verbose_name="Edited in Wikibooks",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikidata_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of items created on Wikidata.",
                null=True,
                verbose_name="Created in Wikidata",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikidata_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of items edited on Wikidata.",
                null=True,
                verbose_name="Edited in Wikidata",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikifunctions_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikifunctions.",
                null=True,
                verbose_name="Created in Wikifunctions",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikifunctions_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikifunctions.",
                null=True,
                verbose_name="Edited in Wikifunctions",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikinews_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikinews.",
                null=True,
                verbose_name="Created in Wikinews",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikinews_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikinews.",
                null=True,
                verbose_name="Edited in Wikinews",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikipedia_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of articles created on Wikipedia.",
                null=True,
                verbose_name="Created in Wikipedia",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikipedia_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of articles edited on Wikipedia.",
                null=True,
                verbose_name="Edited in Wikipedia",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikiquote_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikiquote.",
                null=True,
                verbose_name="Created in Wikiquote",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikiquote_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikiquote.",
                null=True,
                verbose_name="Edited in Wikiquote",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikisource_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikisource.",
                null=True,
                verbose_name="Created in Wikisource",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikisource_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikisource.",
                null=True,
                verbose_name="Edited in Wikisource",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikispecies_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikispecies.",
                null=True,
                verbose_name="Created in Wikispecies",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikispecies_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikispecies.",
                null=True,
                verbose_name="Edited in Wikispecies",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikiversity_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikiversity.",
                null=True,
                verbose_name="Created in Wikiversity",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikiversity_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikiversity.",
                null=True,
                verbose_name="Edited in Wikiversity",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikivoyage_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wikivoyage.",
                null=True,
                verbose_name="Created in Wikivoyage",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wikivoyage_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wikivoyage.",
                null=True,
                verbose_name="Edited in Wikivoyage",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wiktionary_created",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials created on Wiktionary.",
                null=True,
                verbose_name="Created in Wiktionary",
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="wiktionary_edited",
            field=models.IntegerField(
                default=0,
                help_text="Number of pages or materials edited on Wiktionary.",
                null=True,
                verbose_name="Edited in Wiktionary",
            ),
        ),
    ]
