# Generated by Django 5.2.15 on 2026-08-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_alter_metric_commons_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Activity code",
                max_length=20,
                verbose_name="Code",
            ),
            preserve_default=False,
        ),
    ]
