# Generated by Django 5.1.1 on 2025-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0016_metric_number_of_donors_metric_number_of_submissions'),
        ('strategy', '0002_strategicaxis_intentionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='generic_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='related_axis',
            field=models.ManyToManyField(blank=True, related_name='areas', to='strategy.strategicaxis'),
        ),
    ]
