# Generated by Django 5.1.1 on 2025-08-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0017_area_generic_area_alter_area_related_axis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='generic_area',
            new_name='poa_area',
        ),
    ]
