# Generated by Django 5.1.1 on 2025-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0018_rename_generic_area_area_poa_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='counts_for_main_funding',
            field=models.BooleanField(default=False),
        ),
    ]
