# Generated by Django 5.1.1 on 2026-01-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0019_project_counts_for_main_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='related_axis',
        ),
    ]
