# Generated by Django 5.1.1 on 2026-01-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0020_remove_area_related_axis'),
        ('users', '0015_alter_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.AddField(
            model_name='activity',
            name='text_en',
            field=models.CharField(help_text='Activity title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='activity',
            name='text_es',
            field=models.CharField(help_text='Activity title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='activity',
            name='text_pt_br',
            field=models.CharField(help_text='Activity title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='area',
            name='text_en',
            field=models.CharField(help_text='Area title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='area',
            name='text_es',
            field=models.CharField(help_text='Area title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='area',
            name='text_pt_br',
            field=models.CharField(help_text='Area title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='metric',
            name='incubator_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikimedia Incubator.', null=True, verbose_name='Created in Wikimedia Incubator'),
        ),
        migrations.AddField(
            model_name='metric',
            name='incubator_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikimedia Incubator.', null=True, verbose_name='Edited in Wikimedia Incubator'),
        ),
        migrations.AddField(
            model_name='metric',
            name='number_of_new_organizers',
            field=models.IntegerField(default=0, help_text='Number of organizers recently registered', null=True, verbose_name='Number of new organizers'),
        ),
        migrations.AddField(
            model_name='metric',
            name='text_es',
            field=models.CharField(help_text='Metric title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='metric',
            name='text_pt_br',
            field=models.CharField(help_text='Metric title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='metric',
            name='wikifunctions_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on WikiFunctions.', null=True, verbose_name='Created in WikiFunctions'),
        ),
        migrations.AddField(
            model_name='metric',
            name='wikifunctions_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on WikiFunctions.', null=True, verbose_name='Edited in WikiFunctions'),
        ),
        migrations.AddField(
            model_name='project',
            name='active_status',
            field=models.BooleanField(default=True, help_text='Is the project active?', verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_en',
            field=models.CharField(help_text='Project title', max_length=420, null=True, unique=True, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_es',
            field=models.CharField(help_text='Project title', max_length=420, null=True, unique=True, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_pt_br',
            field=models.CharField(help_text='Project title', max_length=420, null=True, unique=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activities', to='metrics.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='area_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_manager', to='users.teamarea', verbose_name='Area responsible'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, help_text='Activity code', max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_main_activity',
            field=models.BooleanField(default=False, help_text='Is this the main activity?', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.CharField(help_text='Activity title', max_length=420, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='area',
            name='poa_area',
            field=models.BooleanField(default=False, help_text='Is this area part of the Plan of Activities?', verbose_name='Part of the Plan of Activities?'),
        ),
        migrations.AlterField(
            model_name='area',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project_activity', to='metrics.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='area',
            name='text',
            field=models.CharField(help_text='Area title', max_length=420, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metrics.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='boolean_type',
            field=models.BooleanField(default=False, help_text='Boolean type metric', verbose_name='Boolean type?'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='commons_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikimedia Commons.', null=True, verbose_name='Created in Wikimedia Commons'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='commons_edited',
            field=models.IntegerField(default=0, help_text='Number of items edited on Wikimedia Commons.', null=True, verbose_name='Edited in Wikimedia Commons'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='is_operation',
            field=models.BooleanField(default=False, help_text='Is the metric an operation metric?', verbose_name='Operation?'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mediawiki_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Mediawiki.', null=True, verbose_name='Created in Mediawiki'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='mediawiki_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Mediawiki.', null=True, verbose_name='Edited in Mediawiki'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metawiki_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Meta-Wiki.', null=True, verbose_name='Created in Meta-Wiki'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metawiki_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Meta-Wiki.', null=True, verbose_name='Edited in Meta-Wiki'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_community_communications',
            field=models.IntegerField(default=0, help_text='Number of communications and newsletters', null=True, verbose_name='Number of community communications'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_donors',
            field=models.IntegerField(default=0, help_text='Number of donors', null=True, verbose_name='Number of donors'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_editors',
            field=models.IntegerField(default=0, help_text='Number of editors', null=True, verbose_name='Number of editors'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_editors_retained',
            field=models.IntegerField(default=0, help_text='Number of editors participating in more activities', null=True, verbose_name='Number of editors retained'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_events',
            field=models.IntegerField(default=0, help_text='Number of activities', null=True, verbose_name='Number of events'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_feedbacks',
            field=models.IntegerField(default=0, help_text='Number of feedbacks', null=True, verbose_name='Number of feedbacks'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_mentions',
            field=models.IntegerField(default=0, help_text='Media clipping', null=True, verbose_name='Number of mentions'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_new_editors',
            field=models.IntegerField(default=0, help_text='Number of editors recently registered', null=True, verbose_name='Number of new editors'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_new_followers',
            field=models.IntegerField(default=0, help_text='Number of new followers in social media', null=True, verbose_name='Number of new followers'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_new_partnerships',
            field=models.IntegerField(default=0, help_text='Number of new partnerships', null=True, verbose_name='Number of new partnerships'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_organizers',
            field=models.IntegerField(default=0, help_text='Number of organizers', null=True, verbose_name='Number of organizers'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_organizers_retained',
            field=models.IntegerField(default=0, help_text='Number of organizers participating in more activities', null=True, verbose_name='Number of organizers retained'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_participants',
            field=models.IntegerField(default=0, help_text='Number of participants', null=True, verbose_name='Number of participants'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_partnerships_activated',
            field=models.IntegerField(default=0, help_text='Number of partnerships activated', null=True, verbose_name='Number of partnerships activated'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_people_reached_through_social_media',
            field=models.IntegerField(default=0, help_text='Number of people reached through social media', null=True, verbose_name='Number of people reached through social media'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_resources',
            field=models.IntegerField(default=0, help_text='Number of resources produced', null=True, verbose_name='Number of resources'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='number_of_submissions',
            field=models.IntegerField(default=0, help_text='Number of grants submissions', null=True, verbose_name='Number of submissions'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='observation',
            field=models.CharField(blank=True, help_text='Observation for this metric', max_length=420, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='other_type',
            field=models.CharField(blank=True, help_text='Other type of metric', max_length=420, null=True, verbose_name='Other type?'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project_associated', to='metrics.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='text',
            field=models.CharField(help_text='Metric title', max_length=420, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='text_en',
            field=models.CharField(help_text='Metric title', max_length=420, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikibooks_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikibooks.', null=True, verbose_name='Created in Wikibooks'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikibooks_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikibooks.', null=True, verbose_name='Edited in Wikibooks'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikidata_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikidata.', null=True, verbose_name='Created in Wikidata'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikidata_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikidata.', null=True, verbose_name='Edited in Wikidata'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikinews_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikinews.', null=True, verbose_name='Created in Wikinews'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikinews_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikinews.', null=True, verbose_name='Edited in Wikinews'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikipedia_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikipedia.', null=True, verbose_name='Created in Wikipedia'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikipedia_edited',
            field=models.IntegerField(default=0, help_text='Number of items edited on Wikipedia.', null=True, verbose_name='Edited in Wikipedia'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikiquote_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikiquote.', null=True, verbose_name='Created in Wikiquote'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikiquote_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikiquote.', null=True, verbose_name='Edited in Wikiquote'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikisource_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikisource.', null=True, verbose_name='Created in Wikisource'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikisource_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikisource.', null=True, verbose_name='Edited in Wikisource'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikispecies_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikispecies.', null=True, verbose_name='Created in Wikispecies'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikispecies_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikispecies.', null=True, verbose_name='Edited in Wikispecies'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikiversity_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikiversity.', null=True, verbose_name='Created in Wikiversity'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikiversity_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikiversity.', null=True, verbose_name='Edited in Wikiversity'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikivoyage_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikivoyage.', null=True, verbose_name='Created in Wikivoyage'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wikivoyage_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wikivoyage.', null=True, verbose_name='Edited in Wikivoyage'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wiktionary_created',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wiktionary.', null=True, verbose_name='Created in Wiktionary'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='wiktionary_edited',
            field=models.IntegerField(default=0, help_text='Number of items created/edited on Wiktionary.', null=True, verbose_name='Edited in Wiktionary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='counts_for_main_funding',
            field=models.BooleanField(default=False, help_text='Does this counts towards Main Funding project metrics?', verbose_name="Counts towards Main Funding project's metrics?"),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_poa',
            field=models.BooleanField(default=False, help_text='Is this the current plan of activities?', verbose_name='Current Plan of Activities'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_funding',
            field=models.BooleanField(default=False, help_text='Is this the main funding project?', verbose_name='Current Main Funding project?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(help_text='Project title', max_length=420, unique=True, verbose_name='Project'),
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
