# Generated by Django 5.1.1 on 2026-01-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0021_remove_project_active_activity_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(help_text='Project title', max_length=210, unique=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text_en',
            field=models.CharField(help_text='Project title', max_length=210, null=True, unique=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text_es',
            field=models.CharField(help_text='Project title', max_length=210, null=True, unique=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text_pt_br',
            field=models.CharField(help_text='Project title', max_length=210, null=True, unique=True, verbose_name='Project'),
        ),
    ]
