# Generated by Django 5.1.1 on 2026-01-04 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0010_alter_bug_status'),
        ('users', '0015_alter_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-report_date', 'status'], 'verbose_name': 'Bug', 'verbose_name_plural': 'Bugs'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='date_of_report',
            new_name='report_date'
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='date_of_answer',
            new_name='answer_date'
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='type_of_bug',
            new_name='bug_type'
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(help_text='Detailed explanation of the problem or request.', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reporter',
            field=models.ForeignKey(editable=False, help_text='User who reported the bug.', on_delete=django.db.models.deletion.RESTRICT, related_name='reporter', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('0', 'To do'), ('1', 'In evaluation'), ('2', 'In progress'), ('3', 'Testing'), ('4', 'Done'), ('5', 'Canceled')], default='1', help_text='Status of the reported issue.', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(help_text='Short, descriptive summary of the issue.', max_length=140, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='update_date',
            field=models.DateField(auto_now=True, help_text='Date when the bug was updated.', verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='bug_report',
            field=models.OneToOneField(help_text='Observation associated with a bug.', on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='bug.bug'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation',
            field=models.TextField(help_text='Resolution notes of final response', max_length=500, verbose_name='Observation'),
        ),
    ]
