# Generated by Django 5.1.1 on 2026-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0011_alter_bug_options_alter_observation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('1', 'Error'), ('2', 'Improvement request'), ('3', 'New feature request'), ('4', 'Question or clarification')], default='1', help_text='Category of the reported issue.', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='report_date',
            field=models.DateField(auto_now_add=True, help_text='Timestamp when the bug was created.', verbose_name='Date of report'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='answer_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of answer of the observation', verbose_name='Date of answer'),
        ),
    ]
